# -*- conf -*-

font=IBM Plex Mono:size=12
initial-color-theme=dark
initial-window-size-pixels=1000x700  # Or,
pad=6x6

[environment]

[security]

[bell]

[desktop-notifications]

[scrollback]

[url]

[cursor]

[mouse]

[touch]

[colors-dark]
alpha=0.6

[colors-light]

[csd]

[key-bindings]

[search-bindings]

[url-bindings]

[text-bindings]

[mouse-bindings]
